package com.moviebooking.movie.domains;

import java.util.ArrayList;
import java.util.List;

import org.apache.commons.text.WordUtils;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;

import lombok.EqualsAndHashCode;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;

@Getter
@Setter
@NoArgsConstructor
@EqualsAndHashCode(onlyExplicitlyIncluded = true)
@DynamoDBTable(tableName = "Location")
public class Location {

	@DynamoDBHashKey
	@DynamoDBAutoGeneratedKey
	private String locationId;

	@DynamoDBAttribute
	@EqualsAndHashCode.Include
	private String city;

	@DynamoDBAttribute
	@EqualsAndHashCode.Include
	private String state;

	@DynamoDBAttribute
	private List<String> theatreIds = new ArrayList<String>();

	@DynamoDBAttribute
	private List<String> movieIds = new ArrayList<String>();
	
	public Location(String city, String state) {
		this.setCity(city);
		this.setState(state);
	}

	public void setCity(String city) {
		this.city = WordUtils.capitalizeFully(city);
	}

	public void setState(String state) {
		this.state = WordUtils.capitalizeFully(state);
	}
}
