package com.moviebooking.movie.domains;

import java.util.HashMap;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;

import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.NonNull;
import lombok.RequiredArgsConstructor;
import lombok.Setter;


@Getter
@Setter
@NoArgsConstructor
@RequiredArgsConstructor
@DynamoDBTable(tableName="MovieTheatres")
public class MovieTheatres {

	@DynamoDBHashKey
	@DynamoDBAutoGeneratedKey
	private String id;
	
	@NonNull
	@DynamoDBAttribute
	private String locationId;
	
	@NonNull
	@DynamoDBAttribute
	private String movieId;
	
	@DynamoDBAttribute
	private HashMap<String, Integer> theatreIds = new HashMap<>();
}
