package com.moviebooking.movie.domains;

import java.util.Calendar;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBIgnore;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBMapperFieldModel.DynamoDBAttributeType;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTypeConvertedEnum;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTyped;
import com.moviebooking.movie.enums.Language;

import lombok.EqualsAndHashCode;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;
import lombok.ToString;

@Getter
@Setter
@NoArgsConstructor
@ToString(includeFieldNames = true)
@EqualsAndHashCode(onlyExplicitlyIncluded = true)
@DynamoDBTable(tableName = "Show")
public class Show {

	@DynamoDBHashKey
	@DynamoDBAutoGeneratedKey
	private String showId;

	@DynamoDBAttribute
	@EqualsAndHashCode.Include
	private Calendar showStartTime;

	@DynamoDBAttribute
	@EqualsAndHashCode.Include
	private Calendar showEndTime;

	@DynamoDBTyped(DynamoDBAttributeType.M)
	@EqualsAndHashCode.Include
	private Movie movie;

	@DynamoDBIgnore
	@EqualsAndHashCode.Include
	private String movieId;

	@DynamoDBTypeConvertedEnum
	@EqualsAndHashCode.Include
	private Language language;

	@DynamoDBAttribute
	@EqualsAndHashCode.Include
	private String theatreId;

}
