package com.moviebooking.movie.domains;

import java.util.ArrayList;
import java.util.List;

import org.apache.commons.text.WordUtils;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;

import lombok.EqualsAndHashCode;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;
import lombok.ToString;

@Getter
@Setter
@NoArgsConstructor
@ToString(includeFieldNames = true)
@EqualsAndHashCode(onlyExplicitlyIncluded = true)
@DynamoDBTable(tableName = "Theatre")
public class Theatre {

	@DynamoDBHashKey
	@DynamoDBAutoGeneratedKey
	private String theatreId;

	@DynamoDBAttribute
	@EqualsAndHashCode.Include
	private String theatreName;

	@DynamoDBAttribute
	private Double rating;

	@DynamoDBAttribute
	private String locationId;

	@DynamoDBAttribute
	@EqualsAndHashCode.Include
	private Address address;

	@DynamoDBAttribute
	private List<Show> shows = new ArrayList<Show>();

	public Theatre(String theatreName, double rating, Address address) {
		super();
		this.theatreName = theatreName;
		this.rating = rating;
		this.address = address;
	}

	public void setTheatreName(String theatreName) {
		this.theatreName = WordUtils.capitalizeFully(theatreName);
	}
}
